server:
  port: 8081

grpc:
  server:
    port: 9005
  client:
    grpc-user-service:
      address: static://User-service:9002
      negotiationType: plaintext
spring:
  data:
    mongodb:
      uri: mongodb://NotificationDb:27017/Notifications
