grpc:
  client:
    grpc-devproblems-service:
      address: static://localhost:9000
      negotiationType: plaintext
    grpc-reservation-service:
      address: static://Reservation-service:9001
      negotiationType: plaintext
    grpc-user-service:
      address: static://User-service:9002
      negotiationType: plaintext
    grpc-accommodation-service:
      address: static://Accommodation-service:9003
      negotiationType: plaintext
    grpc-accommodation-grader-service:
      address: static://Grader-service:9004
      negotiationType: plaintext
    grpc-notification-service:
      address: static://Notification-service:9005
      negotiationType: plaintext
        # address: static://Accommodation-service:9003
        # negotiationType: plaintext

