grpc:
  client:
    grpc-devproblems-service:
      address: static://localhost:9000
      negotiationType: plaintext
    grpc-reservation-service:
      address: static://localhost:9001
      negotiationType: plaintext
    grpc-user-service:
      address: static://localhost:9002
      negotiationType: plaintext
    grpc-accommodation-service:
      address: static://localhost:9003
      negotiationType: plaintext
    grpc-accommodation-grader-service:
      address: static://localhost:9004
      negotiationType: plaintext

