grpc:
  server:
    port: 9003
  client:
    grpc-reservation-service:
      address: static://Reservation-service:9001
      negotiationType: plaintext
spring:
  datasource:
    url: jdbc:postgresql://AccommodationDb:5432/accommodations
    username: postgres
    password: ftn
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create