grpc:
  server:
    port: 9004
  client:
    grpc-accommodation-service:
      address: static://localhost:9003
      negotiationType: plaintext
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/AccommodationGrades