grpc:
  server:
    port: 9004
  client:
    grpc-accommodation-service:
      address: static://Accommodation-service:9003
      negotiationType: plaintext
    grpc-notification-service:
      address: static://Notification-service:9005
      negotiationType: plaintext
spring:
  data:
    mongodb:
      uri: mongodb://GraderDb:27017/AccommodationGrades