grpc:
  server:
    port: 9002
  client:
    grpc-reservation-service:
      address: static://Reservation-service:9001
      negotiationType: plaintext
    grpc-accommodation-service:
      address: static://Accommodation-service:9003
      negotiationType: plaintext
    grpc-accommodation-grader-service:
      address: static://Grader-service:9004
      negotiationType: plaintext
    grpc-notification-service:
      address: static://Notification-service:9005
      negotiationType: plaintext
spring:
  data:
    mongodb:
      uri: mongodb://UserDb:27017/Users
