grpc:
  server:
    port: 9002
  client:
    grpc-reservation-service:
      address: static://Reservation-service:9001
      negotiationType: plaintext
    grpc-accommodation-service:
      address: static://localhost:9003
      negotiationType: plaintext
    grpc-accommodation-grader-service:
      address: static://localhost:9004
      negotiationType: plaintext
    grpc-notification-service:
      address: static://localhost:9005
      negotiationType: plaintext
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/Users
# spring.data.mongodb.uri: mongodb://UserDb:27017/Users
