grpc:
  server:
    port: 9001
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reservations
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update