grpc:
  server:
    port: 9001
  client:
      grpc-user-service:
        address: static://localhost:9002
        negotiationType: plaintext
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reservations
    username: postgres
    password: ftn
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update