// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.devProblems;

public interface isAvailableOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.devProblems.isAvailable)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool available = 1;</code>
   */
  boolean getAvailable();
}
