// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.devProblems;

/**
 * Protobuf type {@code com.devProblems.ReservationResp}
 */
public  final class ReservationResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.devProblems.ReservationResp)
    ReservationRespOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReservationResp.newBuilder() to construct.
  private ReservationResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReservationResp() {
    numberOfGuests_ = 0;
    accommodationId_ = 0;
    status_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReservationResp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (startDate_ != null) {
              subBuilder = startDate_.toBuilder();
            }
            startDate_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(startDate_);
              startDate_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (endDate_ != null) {
              subBuilder = endDate_.toBuilder();
            }
            endDate_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(endDate_);
              endDate_ = subBuilder.buildPartial();
            }

            break;
          }
          case 24: {

            numberOfGuests_ = input.readInt32();
            break;
          }
          case 32: {

            accommodationId_ = input.readInt32();
            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.devProblems.Reservation.internal_static_com_devProblems_ReservationResp_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.devProblems.Reservation.internal_static_com_devProblems_ReservationResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.devProblems.ReservationResp.class, com.devProblems.ReservationResp.Builder.class);
  }

  public static final int START_DATE_FIELD_NUMBER = 1;
  private com.google.protobuf.Timestamp startDate_;
  /**
   * <code>.google.protobuf.Timestamp start_date = 1;</code>
   */
  public boolean hasStartDate() {
    return startDate_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp start_date = 1;</code>
   */
  public com.google.protobuf.Timestamp getStartDate() {
    return startDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : startDate_;
  }
  /**
   * <code>.google.protobuf.Timestamp start_date = 1;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getStartDateOrBuilder() {
    return getStartDate();
  }

  public static final int END_DATE_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp endDate_;
  /**
   * <code>.google.protobuf.Timestamp end_date = 2;</code>
   */
  public boolean hasEndDate() {
    return endDate_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp end_date = 2;</code>
   */
  public com.google.protobuf.Timestamp getEndDate() {
    return endDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : endDate_;
  }
  /**
   * <code>.google.protobuf.Timestamp end_date = 2;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getEndDateOrBuilder() {
    return getEndDate();
  }

  public static final int NUMBEROFGUESTS_FIELD_NUMBER = 3;
  private int numberOfGuests_;
  /**
   * <code>int32 numberOfGuests = 3;</code>
   */
  public int getNumberOfGuests() {
    return numberOfGuests_;
  }

  public static final int ACCOMMODATION_ID_FIELD_NUMBER = 4;
  private int accommodationId_;
  /**
   * <code>int32 accommodation_id = 4;</code>
   */
  public int getAccommodationId() {
    return accommodationId_;
  }

  public static final int STATUS_FIELD_NUMBER = 5;
  private int status_;
  /**
   * <code>.com.devProblems.ReservationStatus status = 5;</code>
   */
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.com.devProblems.ReservationStatus status = 5;</code>
   */
  public com.devProblems.ReservationStatus getStatus() {
    com.devProblems.ReservationStatus result = com.devProblems.ReservationStatus.valueOf(status_);
    return result == null ? com.devProblems.ReservationStatus.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (startDate_ != null) {
      output.writeMessage(1, getStartDate());
    }
    if (endDate_ != null) {
      output.writeMessage(2, getEndDate());
    }
    if (numberOfGuests_ != 0) {
      output.writeInt32(3, numberOfGuests_);
    }
    if (accommodationId_ != 0) {
      output.writeInt32(4, accommodationId_);
    }
    if (status_ != com.devProblems.ReservationStatus.RESERVATION_STATUS_PENDING.getNumber()) {
      output.writeEnum(5, status_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (startDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getStartDate());
    }
    if (endDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getEndDate());
    }
    if (numberOfGuests_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, numberOfGuests_);
    }
    if (accommodationId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, accommodationId_);
    }
    if (status_ != com.devProblems.ReservationStatus.RESERVATION_STATUS_PENDING.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, status_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.devProblems.ReservationResp)) {
      return super.equals(obj);
    }
    com.devProblems.ReservationResp other = (com.devProblems.ReservationResp) obj;

    boolean result = true;
    result = result && (hasStartDate() == other.hasStartDate());
    if (hasStartDate()) {
      result = result && getStartDate()
          .equals(other.getStartDate());
    }
    result = result && (hasEndDate() == other.hasEndDate());
    if (hasEndDate()) {
      result = result && getEndDate()
          .equals(other.getEndDate());
    }
    result = result && (getNumberOfGuests()
        == other.getNumberOfGuests());
    result = result && (getAccommodationId()
        == other.getAccommodationId());
    result = result && status_ == other.status_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStartDate()) {
      hash = (37 * hash) + START_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getStartDate().hashCode();
    }
    if (hasEndDate()) {
      hash = (37 * hash) + END_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getEndDate().hashCode();
    }
    hash = (37 * hash) + NUMBEROFGUESTS_FIELD_NUMBER;
    hash = (53 * hash) + getNumberOfGuests();
    hash = (37 * hash) + ACCOMMODATION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getAccommodationId();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.devProblems.ReservationResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.devProblems.ReservationResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.devProblems.ReservationResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.devProblems.ReservationResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.devProblems.ReservationResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.devProblems.ReservationResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.devProblems.ReservationResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.devProblems.ReservationResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.devProblems.ReservationResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.devProblems.ReservationResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.devProblems.ReservationResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.devProblems.ReservationResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.devProblems.ReservationResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.devProblems.ReservationResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.devProblems.ReservationResp)
      com.devProblems.ReservationRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.devProblems.Reservation.internal_static_com_devProblems_ReservationResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.devProblems.Reservation.internal_static_com_devProblems_ReservationResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.devProblems.ReservationResp.class, com.devProblems.ReservationResp.Builder.class);
    }

    // Construct using com.devProblems.ReservationResp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (startDateBuilder_ == null) {
        startDate_ = null;
      } else {
        startDate_ = null;
        startDateBuilder_ = null;
      }
      if (endDateBuilder_ == null) {
        endDate_ = null;
      } else {
        endDate_ = null;
        endDateBuilder_ = null;
      }
      numberOfGuests_ = 0;

      accommodationId_ = 0;

      status_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.devProblems.Reservation.internal_static_com_devProblems_ReservationResp_descriptor;
    }

    public com.devProblems.ReservationResp getDefaultInstanceForType() {
      return com.devProblems.ReservationResp.getDefaultInstance();
    }

    public com.devProblems.ReservationResp build() {
      com.devProblems.ReservationResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.devProblems.ReservationResp buildPartial() {
      com.devProblems.ReservationResp result = new com.devProblems.ReservationResp(this);
      if (startDateBuilder_ == null) {
        result.startDate_ = startDate_;
      } else {
        result.startDate_ = startDateBuilder_.build();
      }
      if (endDateBuilder_ == null) {
        result.endDate_ = endDate_;
      } else {
        result.endDate_ = endDateBuilder_.build();
      }
      result.numberOfGuests_ = numberOfGuests_;
      result.accommodationId_ = accommodationId_;
      result.status_ = status_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.devProblems.ReservationResp) {
        return mergeFrom((com.devProblems.ReservationResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.devProblems.ReservationResp other) {
      if (other == com.devProblems.ReservationResp.getDefaultInstance()) return this;
      if (other.hasStartDate()) {
        mergeStartDate(other.getStartDate());
      }
      if (other.hasEndDate()) {
        mergeEndDate(other.getEndDate());
      }
      if (other.getNumberOfGuests() != 0) {
        setNumberOfGuests(other.getNumberOfGuests());
      }
      if (other.getAccommodationId() != 0) {
        setAccommodationId(other.getAccommodationId());
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.devProblems.ReservationResp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.devProblems.ReservationResp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.Timestamp startDate_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> startDateBuilder_;
    /**
     * <code>.google.protobuf.Timestamp start_date = 1;</code>
     */
    public boolean hasStartDate() {
      return startDateBuilder_ != null || startDate_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp start_date = 1;</code>
     */
    public com.google.protobuf.Timestamp getStartDate() {
      if (startDateBuilder_ == null) {
        return startDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : startDate_;
      } else {
        return startDateBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp start_date = 1;</code>
     */
    public Builder setStartDate(com.google.protobuf.Timestamp value) {
      if (startDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        startDate_ = value;
        onChanged();
      } else {
        startDateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp start_date = 1;</code>
     */
    public Builder setStartDate(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (startDateBuilder_ == null) {
        startDate_ = builderForValue.build();
        onChanged();
      } else {
        startDateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp start_date = 1;</code>
     */
    public Builder mergeStartDate(com.google.protobuf.Timestamp value) {
      if (startDateBuilder_ == null) {
        if (startDate_ != null) {
          startDate_ =
            com.google.protobuf.Timestamp.newBuilder(startDate_).mergeFrom(value).buildPartial();
        } else {
          startDate_ = value;
        }
        onChanged();
      } else {
        startDateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp start_date = 1;</code>
     */
    public Builder clearStartDate() {
      if (startDateBuilder_ == null) {
        startDate_ = null;
        onChanged();
      } else {
        startDate_ = null;
        startDateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp start_date = 1;</code>
     */
    public com.google.protobuf.Timestamp.Builder getStartDateBuilder() {
      
      onChanged();
      return getStartDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp start_date = 1;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getStartDateOrBuilder() {
      if (startDateBuilder_ != null) {
        return startDateBuilder_.getMessageOrBuilder();
      } else {
        return startDate_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : startDate_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp start_date = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getStartDateFieldBuilder() {
      if (startDateBuilder_ == null) {
        startDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getStartDate(),
                getParentForChildren(),
                isClean());
        startDate_ = null;
      }
      return startDateBuilder_;
    }

    private com.google.protobuf.Timestamp endDate_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> endDateBuilder_;
    /**
     * <code>.google.protobuf.Timestamp end_date = 2;</code>
     */
    public boolean hasEndDate() {
      return endDateBuilder_ != null || endDate_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp end_date = 2;</code>
     */
    public com.google.protobuf.Timestamp getEndDate() {
      if (endDateBuilder_ == null) {
        return endDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : endDate_;
      } else {
        return endDateBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp end_date = 2;</code>
     */
    public Builder setEndDate(com.google.protobuf.Timestamp value) {
      if (endDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        endDate_ = value;
        onChanged();
      } else {
        endDateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp end_date = 2;</code>
     */
    public Builder setEndDate(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (endDateBuilder_ == null) {
        endDate_ = builderForValue.build();
        onChanged();
      } else {
        endDateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp end_date = 2;</code>
     */
    public Builder mergeEndDate(com.google.protobuf.Timestamp value) {
      if (endDateBuilder_ == null) {
        if (endDate_ != null) {
          endDate_ =
            com.google.protobuf.Timestamp.newBuilder(endDate_).mergeFrom(value).buildPartial();
        } else {
          endDate_ = value;
        }
        onChanged();
      } else {
        endDateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp end_date = 2;</code>
     */
    public Builder clearEndDate() {
      if (endDateBuilder_ == null) {
        endDate_ = null;
        onChanged();
      } else {
        endDate_ = null;
        endDateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp end_date = 2;</code>
     */
    public com.google.protobuf.Timestamp.Builder getEndDateBuilder() {
      
      onChanged();
      return getEndDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp end_date = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getEndDateOrBuilder() {
      if (endDateBuilder_ != null) {
        return endDateBuilder_.getMessageOrBuilder();
      } else {
        return endDate_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : endDate_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp end_date = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getEndDateFieldBuilder() {
      if (endDateBuilder_ == null) {
        endDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getEndDate(),
                getParentForChildren(),
                isClean());
        endDate_ = null;
      }
      return endDateBuilder_;
    }

    private int numberOfGuests_ ;
    /**
     * <code>int32 numberOfGuests = 3;</code>
     */
    public int getNumberOfGuests() {
      return numberOfGuests_;
    }
    /**
     * <code>int32 numberOfGuests = 3;</code>
     */
    public Builder setNumberOfGuests(int value) {
      
      numberOfGuests_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 numberOfGuests = 3;</code>
     */
    public Builder clearNumberOfGuests() {
      
      numberOfGuests_ = 0;
      onChanged();
      return this;
    }

    private int accommodationId_ ;
    /**
     * <code>int32 accommodation_id = 4;</code>
     */
    public int getAccommodationId() {
      return accommodationId_;
    }
    /**
     * <code>int32 accommodation_id = 4;</code>
     */
    public Builder setAccommodationId(int value) {
      
      accommodationId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 accommodation_id = 4;</code>
     */
    public Builder clearAccommodationId() {
      
      accommodationId_ = 0;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.com.devProblems.ReservationStatus status = 5;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.com.devProblems.ReservationStatus status = 5;</code>
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.devProblems.ReservationStatus status = 5;</code>
     */
    public com.devProblems.ReservationStatus getStatus() {
      com.devProblems.ReservationStatus result = com.devProblems.ReservationStatus.valueOf(status_);
      return result == null ? com.devProblems.ReservationStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.devProblems.ReservationStatus status = 5;</code>
     */
    public Builder setStatus(com.devProblems.ReservationStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.devProblems.ReservationStatus status = 5;</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.devProblems.ReservationResp)
  }

  // @@protoc_insertion_point(class_scope:com.devProblems.ReservationResp)
  private static final com.devProblems.ReservationResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.devProblems.ReservationResp();
  }

  public static com.devProblems.ReservationResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReservationResp>
      PARSER = new com.google.protobuf.AbstractParser<ReservationResp>() {
    public ReservationResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReservationResp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReservationResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReservationResp> getParserForType() {
    return PARSER;
  }

  public com.devProblems.ReservationResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

