// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.devProblems;

public final class Reservation {
  private Reservation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_devProblems_ReservationReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_devProblems_ReservationReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_devProblems_ReservationResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_devProblems_ReservationResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_devProblems_isAvailable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_devProblems_isAvailable_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021reservation.proto\022\017com.devProblems\032\037go" +
      "ogle/protobuf/timestamp.proto\"\240\001\n\016Reserv" +
      "ationReq\022.\n\nstart_date\030\001 \001(\0132\032.google.pr" +
      "otobuf.Timestamp\022,\n\010end_date\030\002 \001(\0132\032.goo" +
      "gle.protobuf.Timestamp\022\026\n\016numberOfGuests" +
      "\030\003 \001(\005\022\030\n\020accommodation_id\030\004 \001(\005\"\325\001\n\017Res" +
      "ervationResp\022.\n\nstart_date\030\001 \001(\0132\032.googl" +
      "e.protobuf.Timestamp\022,\n\010end_date\030\002 \001(\0132\032" +
      ".google.protobuf.Timestamp\022\026\n\016numberOfGu" +
      "ests\030\003 \001(\005\022\030\n\020accommodation_id\030\004 \001(\005\0222\n\006" +
      "status\030\005 \001(\0162\".com.devProblems.Reservati" +
      "onStatus\" \n\013isAvailable\022\021\n\tavailable\030\001 \001" +
      "(\010*\266\001\n\021ReservationStatus\022\036\n\032RESERVATION_" +
      "STATUS_PENDING\020\000\022\037\n\033RESERVATION_STATUS_A" +
      "CCEPTED\020\001\022\037\n\033RESERVATION_STATUS_DECLINED" +
      "\020\002\022\036\n\032RESERVATION_STATUS_DELETED\020\003\022\037\n\033RE" +
      "SERVATION_STATUS_CANCELED\020\0042\300\001\n\022Reservat" +
      "ionService\022V\n\021CreateReservation\022\037.com.de" +
      "vProblems.ReservationReq\032 .com.devProble" +
      "ms.ReservationResp\022R\n\021CheckAvailability\022" +
      "\037.com.devProblems.ReservationReq\032\034.com.d" +
      "evProblems.isAvailableB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_com_devProblems_ReservationReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_devProblems_ReservationReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_devProblems_ReservationReq_descriptor,
        new java.lang.String[] { "StartDate", "EndDate", "NumberOfGuests", "AccommodationId", });
    internal_static_com_devProblems_ReservationResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_devProblems_ReservationResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_devProblems_ReservationResp_descriptor,
        new java.lang.String[] { "StartDate", "EndDate", "NumberOfGuests", "AccommodationId", "Status", });
    internal_static_com_devProblems_isAvailable_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_devProblems_isAvailable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_devProblems_isAvailable_descriptor,
        new java.lang.String[] { "Available", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
