// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.devProblems;

public final class ReservationOuterClass {
  private ReservationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_devProblems_Reservation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_devProblems_Reservation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021reservation.proto\022\017com.devProblems\032\037go" +
      "ogle/protobuf/timestamp.proto\"\271\001\n\013Reserv" +
      "ation\022.\n\nstart_date\030\001 \001(\0132\032.google.proto" +
      "buf.Timestamp\022,\n\010end_date\030\002 \001(\0132\032.google" +
      ".protobuf.Timestamp\0222\n\006status\030\003 \001(\0162\".co" +
      "m.devProblems.ReservationStatus\022\030\n\020accom" +
      "modation_id\030\004 \001(\005*u\n\021ReservationStatus\022\036" +
      "\n\032RESERVATION_STATUS_PENDING\020\000\022\037\n\033RESERV" +
      "ATION_STATUS_ACCEPTED\020\001\022\037\n\033RESERVATION_S" +
      "TATUS_DECLINED\020\0022\024\n\022ReservationServiceB\002" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_com_devProblems_Reservation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_devProblems_Reservation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_devProblems_Reservation_descriptor,
        new java.lang.String[] { "StartDate", "EndDate", "Status", "AccommodationId", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
